[ci] Update the OpenSUSE Tumbleweed files, but disable it anyway
Another problem on tumbleweed where the required packages can't even
install without zypper giving an error like:

Installation of dbus-1-1.12.20-5.1.x86_64 failed:
Error: Subprocess failed. Error: RPM failed: ERROR: neither useradd nor busybox found!
error: %prein(dbus-1-1.12.20-5.1.x86_64) scriptlet failed, exit status 1
error: dbus-1-1.12.20-5.1.x86_64: install failed

Abort, retry, ignore? [a/r/i] (a): a
Problem occurred during or after installation or removal of packages:
Installation has been aborted as directed.
Please see the above error message for a hint.

I have seen this stuff before and it usually gets sorted out in a
couple days, but to me tumbleweed is too unreliable to keep in the CI
environment.  I will leave leap enabled to get some opensuse coverage.
But for now I am back to turning off tumbleweed as a build target.

Signed-off-by: David Cantrell <dcantrell@redhat.com>