[ci] On alpinelinux, run git config to define the safe directory
This error started showing up on Alpine Linux builds:

  hint: Using 'master' as the name for the initial branch. This default branch name
  hint: is subject to change. To configure the initial branch name to use in all
  hint: of your new repositories, which will suppress this warning, call:
  hint:
  hint:         git config --global init.defaultBranch <name>
  hint:
  hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
  hint: 'development'. The just-created branch can be renamed via this command:
  hint:
  hint:         git branch -m <name>
  Initialized empty Git repository in /__w/rpminspect/rpminspect/.git/
  /usr/bin/git remote add origin https://github.com/rpminspect/rpminspect
  Error: fatal: unsafe repository ('/__w/rpminspect/rpminspect' is owned by someone else)
  To add an exception for this directory, call:

        git config --global --add safe.directory /__w/rpminspect/rpminspect
  Error: The process '/usr/bin/git' failed with exit code 128

This commit does what this error suggests doing in an effort to try
and deal with it.

Signed-off-by: David Cantrell <dcantrell@redhat.com>